packages:
  - 'packages/*'
  - 'website'

allowBuilds:
  es5-ext: false
  esbuild: false
  sharp: true

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@sanity/*'
  - 'use-effect-event'
  # Renovate security update: next@15.5.18
  - next@15.5.18
