export default {
  '-- basics': {type: 'separator', title: 'Basics'},
  'simple': 'First steps',
  'basic-state': 'Basic state',
  'timers': 'Timers & time ago',
  '-- real-world': {type: 'separator', title: 'Real-world'},
  'llm-chat': 'LLM chat streaming',
  'resilient-fetch': 'Offline-resilient fetch',
  'search': 'Search',
  'fetch': 'Fetch requests',
  'form-data': 'Form state',
  'todo-app': 'Todo app',
  'errors': 'Error handling',
  '-- react-integration': {type: 'separator', title: 'React integration'},
  'suspense': 'Suspense & deferred values',
  'data-fetching': 'Suspense data fetching',
  'activity': 'Activity and preload',
  'async-react': 'Async React demo',
  'context': 'React context',
}
