export default {
  'simple': 'Read your first observable',
  'sync': 'Synchronous emissions',
  'event-handlers': 'Read mouse events',
  'counters': 'Compose timer streams',
  'search': 'Search as you type',
  'todo-app': 'Build a list from events',
  'form-data': 'Save form data',
  'context': 'Share a stream with context',
  'fetch': 'Fetch on demand',
  'errors': 'Handle observable errors',
  'suspense': 'Keep results visible',
  'data-fetching': 'Load data with Suspense',
  'transitions': 'Transitions and refetching',
  'activity': 'Activity and preload',
  'animation': 'Animate with a timer',
}
