export default {
  '-- basics': {type: 'separator', title: 'Basics'},
  'simple': 'Simple',
  'counters': 'Advanced counters',
  'sync': 'Sync rendering',
  'event-handlers': 'Events to streams',
  '-- real-world': {type: 'separator', title: 'Real-world'},
  'llm-chat': 'LLM chat streaming',
  'relative-time': 'Relative time',
  'resilient-fetch': 'Offline-resilient fetch',
  'search': 'Search',
  'fetch': 'Fetch requests',
  'form-data': 'Form state',
  'todo-app': 'Todo app',
  'errors': 'Error handling',
  '-- react-integration': {type: 'separator', title: 'React integration'},
  'suspense': 'Suspense & deferred values',
  'data-fetching': 'Suspense data fetching',
  'activity': 'Activity and preload',
  'context': 'React context',
}
