name: CI

on:
  # Build on pushes branches that have a PR (including drafts)
  pull_request:
  # Build on commits pushed to the default branch and the prerelease branch
  push:
    branches: [current, next]

permissions:
  contents: read # for checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm knip --reporter github-actions

  demo:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm install --frozen-lockfile
        working-directory: async-react
      - run: node_modules/.bin/tsc --noEmit -p async-react/tsconfig.json
      - run: pnpm lint
        working-directory: async-react
      - run: pnpm build
        working-directory: async-react

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        runtime: [node@lts]
        include:
          - os: ubuntu-latest
            runtime: node@latest
    steps:
      - name: Set git to use LF
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          runtime: ${{ matrix.runtime }}
      - run: pnpm test
