---
name: Format

on:
  push:
    branches: [current]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  if-needed:
    uses: sanity-io/.github/.github/workflows/format.yml@main
    secrets: inherit
