name: Release

on:
  push:
    branches:
      - current
      # Prerelease branch for the next major, in changesets pre mode (publishes to the `next` dist-tag)
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  release:
    uses: sanity-io/.github/.github/workflows/changesets.yml@main
    permissions:
      contents: read # for checkout
      id-token: write # to enable use of OIDC for npm provenance
    secrets: inherit
